
spring:
  application:
    name: currencies_converter

feign:
  client:
    config:
      currencyClient:
        url: http://www.cbr.ru
        endpoint: /scripts/XML_daily.asp #?date_req=07/10/2024

  cache:
    cache-names: currencyRates
    simple:
      ttl: 3600

resilience4j:
  circuitbreaker:
    instances:
      currencyService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000ms
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3