/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.tbank;

import org.junit.Test;

import java.lang.reflect.Method;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAMain() {
        Method mainMethod = null;
        try {
            mainMethod = Class.forName("ru.tbank.App").getDeclaredMethod("main", String[].class);
        } catch (NoSuchMethodException | ClassNotFoundException e) {
            throw new RuntimeException(e);
        }
        assertNotNull("App should have a main method", mainMethod);    }
}
