/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.tbank;

//import lombok.*;
//import com.fasterxml.jackson.databind.ObjectMapper;
//import org.slf4j.Logger;
//import org.slf4j.LoggerFactory;

public class App {
//    private static final Logger logger = LoggerFactory.getLogger(App.class);
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
